// @ts-check
// Dummy parameters for the step 0.3 inspector demo. Not a real effect — real effect schemas
// live in src/effects/<family>/schema.js from Phase 3 on.
import { defineSchema } from '../src/schema/index.js';

export const demoSchema = defineSchema([
  {
    id: 'demo.count',
    label: 'Count',
    group: 'Shape',
    type: 'int',
    min: 1,
    max: 24,
    default: 8,
    randomize: { min: 5, max: 14 },
    tooltip: 'How many shapes are drawn',
  },
  {
    id: 'demo.size',
    label: 'Size',
    group: 'Shape',
    type: 'float',
    min: 0.1,
    max: 2,
    step: 0.01,
    default: 1,
    randomize: { min: 0.8, max: 1.3 },
    unit: 'x',
    tooltip: 'Overall scale of each shape',
  },
  {
    id: 'demo.spread',
    label: 'Spread',
    group: 'Shape',
    type: 'float',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.6,
    randomize: { min: 0.3, max: 0.9 },
    tooltip: 'Distance of the shapes from the centre',
  },
  {
    id: 'demo.shape',
    label: 'Shape',
    group: 'Shape',
    type: 'enum',
    options: [
      { value: 'circle', label: 'Circle' },
      { value: 'square', label: 'Square' },
      { value: 'star', label: 'Star' },
    ],
    default: 'circle',
    randomize: true,
    tooltip: 'Which shape to draw',
  },
  {
    id: 'demo.rotation',
    label: 'Rotation',
    group: 'Shape',
    type: 'float',
    min: 0,
    max: 360,
    step: 1,
    default: 0,
    randomize: { min: 0, max: 360 },
    unit: '°',
  },
  {
    id: 'demo.color',
    label: 'Fill colour',
    group: 'Style',
    type: 'color',
    default: '#ff8a3d',
  },
  {
    id: 'demo.outline',
    label: 'Outline',
    group: 'Style',
    type: 'bool',
    default: true,
    randomize: { chance: 0.5 },
  },
  {
    id: 'demo.outlinePx',
    label: 'Outline width',
    group: 'Style',
    type: 'int',
    min: 0,
    max: 8,
    default: 2,
    unit: 'px',
  },
  {
    id: 'demo.ramp',
    label: 'Heat ramp',
    group: 'Style',
    type: 'ramp',
    default: [
      { pos: 0, color: '#ffffff' },
      { pos: 0.2, color: '#ffe066' },
      { pos: 0.45, color: '#ff8a3d' },
      { pos: 0.7, color: '#d6332a' },
      { pos: 1, color: '#4a1414' },
    ],
    tooltip: 'Preview only — the ramp editor arrives in step 2.1',
  },
  {
    id: 'demo.scaleOverLife',
    label: 'Scale over life',
    group: 'Motion',
    type: 'curve',
    default: [
      { x: 0, y: 0 },
      { x: 0.15, y: 1 },
      { x: 1, y: 0.5 },
    ],
    tooltip: 'Preview only — the curve editor arrives later',
  },
  {
    id: 'demo.seed',
    label: 'Seed',
    group: 'Variation',
    type: 'seed',
    default: 482913,
    randomize: true,
    tooltip: 'Drives the per-shape size variation',
  },
]);
