// @ts-check
/**
 * Anime Blast (D-114): authored by Raul in the editor (saved as "fire magic 01", v0.0.86) and
 * shipped as-is, minus the four switched-off layers (Smoke, Fireball, Curl wisps, Twinkles).
 * Loaded through `parseExplosion`, exactly like opening the file.
 */

export const ANIME_BLAST_FILE = {
  format: 'eldr-vfx',
  version: 4,
  app: 'ELDR',
  appVersion: '0.0.86',
  family: 'explosion',
  name: 'Anime Blast',
  seed: 482913,
  canvas: {
    w: 512,
    h: 512,
  },
  globals: {
    'explosion.size': 1.13,
    'explosion.impact': 0.13,
    'explosion.flashFrames': 2,
    'explosion.anticipation': true,
    'pixel.enabled': false,
    'pixel.size': 64,
    'pixel.alphaCutoff': 0.4,
    'pixel.palette': 'auto',
    'pixel.colors': 8,
    'pixel.dither': 'none',
    'pixel.ditherStrength': 0.5,
    'pixel.outline': 'none',
    'pixel.outlineColor': '#00000000',
    'pixel.cleanup': true,
    'pixel.snap': true,
    'pixel.snapParticles': false,
    'pixel.customPalette': [
      {
        pos: 0,
        color: '#000000',
      },
      {
        pos: 1,
        color: '#ffffff',
      },
    ],
    'light.alpha': 'unmult',
  },
  timing: {
    holdMode: 'ones',
    frameCount: 70,
    fps: 30,
    loop: false,
    duration: 0.9583333333333334,
    phases: {
      impact: 0.13,
      decay: 0.5800000000000001,
    },
  },
  layers: [
    {
      id: 'shockwave',
      label: 'Shockwave',
      type: 'ring',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'normal',
      anchor: 'afterImpact',
      seedKey: 'shockwave~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: null,
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {},
      params: {
        'ring.radius': 157,
        'ring.thickness': 0.26,
        'ring.thicknessOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.15182117474916387,
            y: 1,
          },
          {
            x: 0.5611935618729097,
            y: 0.19318704044117646,
          },
          {
            x: 1,
            y: 0.2,
          },
        ],
        'ring.breaks': 0,
        'ring.gap': 0.1,
        'ring.distortion': 0,
        'ring.wobble': 0.55,
        'tex.size': 139,
        'tex.play': 'loop',
        'tex.fps': 14,
        'tex.randomStart': true,
        'tex.color': 'original',
        'tex.angle': 0,
        'style.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#d6fff0',
          },
          {
            pos: 0.5,
            color: '#3affb8',
          },
          {
            pos: 0.75,
            color: '#1ab87a',
          },
          {
            pos: 1,
            color: '#0f4a4a',
          },
        ],
        'style.rampOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'style.spread': 0.49,
        'style.bands': 3,
        'style.bandNoise': 0.26,
        'style.snapColors': false,
        'shade.light': 360,
        'shade.shadow': 0,
        'shade.shadowOffset': 0.1,
        'shade.highlight': 0,
        'shade.highlightSize': 0.6,
        'shade.highlightOffset': 0.36,
        'goo.amount': 0,
        'goo.threshold': 0.26,
        'goo.softness': 0.05,
        'goo.keepShapes': true,
        'surf.on': false,
        'surf.map': 'flow',
        'surf.blend': 'normal',
        'surf.mix': 60,
        'surf.flowAngle': -75,
        'surf.flowSpeed': 329,
        'surf.flowStretch': 2.3,
        'surf.radius': 0,
        'surf.spin': 0.1,
        'surf.tilt': 17,
        'surf.type': 'basic',
        'surf.contrast': 198,
        'surf.brightness': -14,
        'surf.invert': false,
        'surf.complexity': 3.3,
        'surf.subInfluence': 42,
        'surf.subScaling': 78,
        'surf.subRotation': 34,
        'surf.scale': 76,
        'surf.stretchW': 129,
        'surf.stretchH': 105,
        'surf.rotation': 0,
        'surf.offsetX': 0,
        'surf.offsetY': 0,
        'surf.flowX': 0,
        'surf.flowY': 0,
        'surf.evolution': 0,
        'surf.evoSpeed': 1.27,
        'surf.warp': 1.34,
        'surf.bands': 5,
        'surf.bandSoft': 0,
        'surf.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#ffe0f0',
          },
          {
            pos: 0.5,
            color: '#ff6ac8',
          },
          {
            pos: 0.75,
            color: '#e01a8a',
          },
          {
            pos: 1,
            color: '#6b0f4a',
          },
        ],
        'surf.alpha': 'luma',
        'surf.quality': 'normal',
        'outline.mode': 'off',
        'outline.px': 1.5,
        'outline.colorMode': 'darken',
        'outline.darken': 0.86,
        'outline.color': '#1a0e12',
        'dissolve.mode': 'off',
        'dissolve.direction': 'dissolve',
        'dissolve.amount': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.45,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'dissolve.size': 31,
        'dissolve.angle': 0,
        'dissolve.roughness': 0.16,
        'dissolve.flow': 0.55,
        'dissolve.edgePx': 0,
        'dissolve.edgeColor': '#fff4c2',
        'dissolve.edgeNoise': 0,
        'dissolve.edgeDetail': 0.65,
        'dissolve.edgeWobble': 0.6,
        'glow.amount': 0,
        'glow.radius': 35,
        'glow.core': 0.84,
        'glow.tint': '#ffffff00',
        'single.start': 0,
        'single.end': 0.54,
        'single.scaleOverLife': [
          {
            x: 0,
            y: 0.15,
          },
          {
            x: 0.35,
            y: 0.85,
          },
          {
            x: 1,
            y: 1.25,
          },
        ],
        'single.opacityOverLife': [
          {
            x: 0,
            y: 1,
          },
          {
            x: 0.6,
            y: 0.9,
          },
          {
            x: 1,
            y: 0,
          },
        ],
        'single.x': 0,
        'single.y': 0,
        'single.rotation': 0,
        'single.scale': 1,
      },
    },
    {
      id: 'shockwave-2',
      label: 'Shockwave copy',
      type: 'ring',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'normal',
      anchor: 'afterImpact',
      seedKey: 'shockwave~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: null,
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {},
      params: {
        'ring.radius': 103,
        'ring.thickness': 0.15,
        'ring.thicknessOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.15182117474916387,
            y: 1,
          },
          {
            x: 0.5611935618729097,
            y: 0.19318704044117646,
          },
          {
            x: 1,
            y: 0.2,
          },
        ],
        'ring.breaks': 0,
        'ring.gap': 0.05,
        'ring.distortion': 0,
        'ring.wobble': 0.55,
        'tex.size': 129,
        'tex.play': 'loop',
        'tex.fps': 44,
        'tex.randomStart': true,
        'tex.color': 'original',
        'tex.angle': 0,
        'style.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#d6fff0',
          },
          {
            pos: 0.5,
            color: '#3affb8',
          },
          {
            pos: 0.75,
            color: '#1ab87a',
          },
          {
            pos: 1,
            color: '#0f4a4a',
          },
        ],
        'style.rampOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'style.spread': 0.32,
        'style.bands': 2,
        'style.bandNoise': 0.14,
        'style.snapColors': false,
        'shade.light': 288,
        'shade.shadow': 0,
        'shade.shadowOffset': 0.34,
        'shade.highlight': 0,
        'shade.highlightSize': 0.2,
        'shade.highlightOffset': 0.61,
        'goo.amount': 0,
        'goo.threshold': 0.53,
        'goo.softness': 0.035,
        'goo.keepShapes': true,
        'surf.on': false,
        'surf.map': 'flow',
        'surf.blend': 'normal',
        'surf.mix': 100,
        'surf.flowAngle': -120,
        'surf.flowSpeed': 178,
        'surf.flowStretch': 2.8,
        'surf.radius': 0,
        'surf.spin': 0.13,
        'surf.tilt': 12,
        'surf.type': 'basic',
        'surf.contrast': 178,
        'surf.brightness': -16,
        'surf.invert': false,
        'surf.complexity': 1.8,
        'surf.subInfluence': 54,
        'surf.subScaling': 57,
        'surf.subRotation': 17,
        'surf.scale': 69,
        'surf.stretchW': 182,
        'surf.stretchH': 83,
        'surf.rotation': 0,
        'surf.offsetX': 0,
        'surf.offsetY': 0,
        'surf.flowX': 0,
        'surf.flowY': 0,
        'surf.evolution': 0,
        'surf.evoSpeed': 1.09,
        'surf.warp': 1.91,
        'surf.bands': 5,
        'surf.bandSoft': 0,
        'surf.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#ffe0f0',
          },
          {
            pos: 0.5,
            color: '#ff6ac8',
          },
          {
            pos: 0.75,
            color: '#e01a8a',
          },
          {
            pos: 1,
            color: '#6b0f4a',
          },
        ],
        'surf.alpha': 'luma',
        'surf.quality': 'normal',
        'outline.mode': 'off',
        'outline.px': 3.5,
        'outline.colorMode': 'darken',
        'outline.darken': 0.6,
        'outline.color': '#1a0e12',
        'dissolve.mode': 'off',
        'dissolve.direction': 'dissolve',
        'dissolve.amount': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.45,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'dissolve.size': 39,
        'dissolve.angle': 0,
        'dissolve.roughness': 0.39,
        'dissolve.flow': 0.3,
        'dissolve.edgePx': 0,
        'dissolve.edgeColor': '#fff4c2',
        'dissolve.edgeNoise': 0,
        'dissolve.edgeDetail': 0.6,
        'dissolve.edgeWobble': 0.95,
        'glow.amount': 0,
        'glow.radius': 16,
        'glow.core': 0.66,
        'glow.tint': '#ffffff00',
        'single.start': 0,
        'single.end': 0.4,
        'single.scaleOverLife': [
          {
            x: 0,
            y: 0.15,
          },
          {
            x: 0.16119356187290967,
            y: 1.0995404411764704,
          },
          {
            x: 0.4565739966555184,
            y: 0.5490579044117647,
          },
          {
            x: 1,
            y: 0.506548713235294,
          },
        ],
        'single.opacityOverLife': [
          {
            x: 0,
            y: 1,
          },
          {
            x: 0.6,
            y: 0.9,
          },
          {
            x: 1,
            y: 0,
          },
        ],
        'single.x': 0,
        'single.y': 0,
        'single.rotation': 0,
        'single.scale': 1,
      },
    },
    {
      id: 'core',
      label: 'magic 01',
      type: 'fieldFire',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'add',
      anchor: 'afterImpact',
      seedKey: 'core~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: 'null',
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {},
      params: {
        'field.form': 'ball',
        'field.width': 103,
        'field.height': 156,
        'field.warp': 1,
        'field.scale': 1.86,
        'field.speed': 4.25,
        'field.bend': 0,
        'field.bendWaves': 1,
        'field.bendTravel': 1,
        'field.lean': 0,
        'field.curl': -8,
        'field.curlHeight': 1.11,
        'field.curlSize': 0.38,
        'field.erode': 1.67,
        'field.erodeOverLife': [
          {
            x: 0,
            y: 0.6,
          },
          {
            x: 0.5,
            y: 1,
          },
          {
            x: 1,
            y: 2.2,
          },
        ],
        'field.swirl': 0.75,
        'field.cool': 1.25,
        'style.ramp': [
          {
            pos: 0,
            color: '#eaffc4',
          },
          {
            pos: 0.25,
            color: '#9be04a',
          },
          {
            pos: 0.5,
            color: '#5a9a5a',
          },
          {
            pos: 0.75,
            color: '#5a3a7a',
          },
          {
            pos: 1,
            color: '#2a1440',
          },
        ],
        'style.rampOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 1,
            y: 0.45,
          },
        ],
        'style.bands': 3,
        'style.snapColors': false,
        'outline.mode': 'off',
        'outline.px': 2,
        'outline.colorMode': 'darken',
        'outline.darken': 0.36,
        'outline.color': '#1a0e12',
        'dissolve.mode': 'off',
        'dissolve.direction': 'dissolve',
        'dissolve.amount': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.45,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'dissolve.size': 38,
        'dissolve.angle': 0,
        'dissolve.roughness': 0.42,
        'dissolve.flow': 0.85,
        'dissolve.edgePx': 0,
        'dissolve.edgeColor': '#fff4c2',
        'dissolve.edgeNoise': 0,
        'dissolve.edgeDetail': 0.7,
        'dissolve.edgeWobble': 0.3,
        'glow.amount': 2.8,
        'glow.radius': 38,
        'glow.core': 0.32,
        'glow.tint': '#ffffff00',
        'single.start': 0,
        'single.end': 0.5,
        'single.scaleOverLife': [
          {
            x: 0,
            y: 0.35,
          },
          {
            x: 0.15,
            y: 1.1,
          },
          {
            x: 0.4,
            y: 1,
          },
          {
            x: 1,
            y: 0.8,
          },
        ],
        'single.opacityOverLife': [
          {
            x: 0,
            y: 1,
          },
          {
            x: 0.85,
            y: 1,
          },
          {
            x: 1,
            y: 0,
          },
        ],
        'single.x': 0,
        'single.y': 0,
        'single.rotation': 0,
        'single.scale': 1,
      },
    },
    {
      id: 'core-2',
      label: 'magic 02',
      type: 'fieldFire',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'add',
      anchor: 'afterImpact',
      seedKey: 'core~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: 'null',
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {},
      params: {
        'field.form': 'ball',
        'field.width': 128,
        'field.height': 423,
        'field.warp': 1,
        'field.scale': 1.35,
        'field.speed': 2.8,
        'field.bend': 0,
        'field.bendWaves': 1.25,
        'field.bendTravel': 0.9,
        'field.lean': 0,
        'field.curl': -7.15,
        'field.curlHeight': 1.44,
        'field.curlSize': 0.27,
        'field.erode': 0.77,
        'field.erodeOverLife': [
          {
            x: 0,
            y: 0.6,
          },
          {
            x: 0.5,
            y: 1,
          },
          {
            x: 1,
            y: 2.2,
          },
        ],
        'field.swirl': 0.54,
        'field.cool': 0.62,
        'style.ramp': [
          {
            pos: 0,
            color: '#eaffc4',
          },
          {
            pos: 0.25,
            color: '#9be04a',
          },
          {
            pos: 0.5,
            color: '#5a9a5a',
          },
          {
            pos: 0.75,
            color: '#5a3a7a',
          },
          {
            pos: 1,
            color: '#2a1440',
          },
        ],
        'style.rampOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 1,
            y: 0.45,
          },
        ],
        'style.bands': 6,
        'style.snapColors': false,
        'outline.mode': 'off',
        'outline.px': 1,
        'outline.colorMode': 'darken',
        'outline.darken': 0.86,
        'outline.color': '#1a0e12',
        'dissolve.mode': 'off',
        'dissolve.direction': 'dissolve',
        'dissolve.amount': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.45,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'dissolve.size': 54,
        'dissolve.angle': 0,
        'dissolve.roughness': 0.15,
        'dissolve.flow': 0.75,
        'dissolve.edgePx': 0,
        'dissolve.edgeColor': '#fff4c2',
        'dissolve.edgeNoise': 0,
        'dissolve.edgeDetail': 0.6,
        'dissolve.edgeWobble': 0.35,
        'glow.amount': 2.88,
        'glow.radius': 52,
        'glow.core': 0.28,
        'glow.tint': '#ffffff00',
        'single.start': 0,
        'single.end': 0.5,
        'single.scaleOverLife': [
          {
            x: 0,
            y: 0.35,
          },
          {
            x: 0.15,
            y: 1.1,
          },
          {
            x: 0.4,
            y: 1,
          },
          {
            x: 1,
            y: 0.8,
          },
        ],
        'single.opacityOverLife': [
          {
            x: 0,
            y: 1,
          },
          {
            x: 0.85,
            y: 1,
          },
          {
            x: 1,
            y: 0,
          },
        ],
        'single.x': 0,
        'single.y': 0,
        'single.rotation': -179,
        'single.scale': 1,
      },
    },
    {
      id: 'null',
      label: 'magic parent',
      type: 'null',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'normal',
      anchor: 'afterImpact',
      seedKey: 'null~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: null,
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {
        'transform.scaleX': [
          {
            t: 0.13333333333333333,
            v: 54.7831794515928,
            ease: 'ease',
          },
          {
            t: 0.43333333333333335,
            v: 118,
            ease: 'ease',
          },
          {
            t: 0.5416666666666666,
            v: 100,
            ease: 'ease',
          },
          {
            t: 0.7333333333333333,
            v: 83,
            ease: 'ease',
          },
        ],
        'transform.scaleY': [
          {
            t: 0.13333333333333333,
            v: 54.7831794515928,
            ease: 'ease',
          },
          {
            t: 0.43333333333333335,
            v: 118,
            ease: 'ease',
          },
          {
            t: 0.5416666666666666,
            v: 100,
            ease: 'ease',
          },
          {
            t: 0.7333333333333333,
            v: 83,
            ease: 'ease',
          },
        ],
        'transform.rotation': [
          {
            t: 0.13333333333333333,
            v: 0,
            ease: 'ease',
          },
          {
            t: 0.5416666666666666,
            v: 360,
            ease: 'ease',
          },
          {
            t: 0.7333333333333333,
            v: 434.483856842151,
            ease: 'ease',
          },
        ],
      },
      params: {},
    },
    {
      id: 'orbitCrescent',
      label: 'Orbit crescents',
      type: 'orbitCrescent',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'add',
      anchor: 'afterImpact',
      seedKey: 'orbitCrescent~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: null,
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {},
      params: {
        'crescent.radius': 491,
        'crescent.sweep': 77,
        'crescent.thickness': 24.5,
        'crescent.thicknessOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.1679426212374582,
            y: 2,
          },
          {
            x: 0.5300088837792643,
            y: 0.09535845588235294,
          },
          {
            x: 1,
            y: 0,
          },
        ],
        'crescent.balance': 0.75,
        'crescent.sharpness': 0.85,
        'crescent.hook': 0,
        'crescent.hotEdge': 0.46,
        'crescent.wobble': 0.13,
        'crescent.wobbleSpeed': 2.8,
        'crescent.reverse': false,
        'crescent.reveal': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.18105926003344483,
            y: 1,
          },
          {
            x: 0.5471754807692307,
            y: 0.08455882352941178,
          },
          {
            x: 1,
            y: 0,
          },
        ],
        'orbit.followPath': true,
        'tex.size': 60,
        'tex.play': 'loop',
        'tex.fps': 19,
        'tex.randomStart': true,
        'tex.color': 'original',
        'tex.angle': 0,
        'style.ramp': [
          {
            pos: 0,
            color: '#eaffc4',
          },
          {
            pos: 0.25,
            color: '#9be04a',
          },
          {
            pos: 0.5,
            color: '#5a9a5a',
          },
          {
            pos: 0.75,
            color: '#5a3a7a',
          },
          {
            pos: 1,
            color: '#2a1440',
          },
        ],
        'style.rampOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 1,
            y: 0.2,
          },
        ],
        'style.spread': 0.4,
        'style.bands': 3,
        'style.bandNoise': 0.13,
        'style.snapColors': false,
        'shade.light': 360,
        'shade.shadow': 0,
        'shade.shadowOffset': 0.12,
        'shade.highlight': 0,
        'shade.highlightSize': 0.38,
        'shade.highlightOffset': 0.25,
        'goo.amount': 0,
        'goo.threshold': 0.37,
        'goo.softness': 0.04,
        'goo.keepShapes': true,
        'surf.on': false,
        'surf.map': 'flow',
        'surf.blend': 'normal',
        'surf.mix': 100,
        'surf.flowAngle': -104,
        'surf.flowSpeed': 169,
        'surf.flowStretch': 1.7,
        'surf.radius': 0,
        'surf.spin': 0.15,
        'surf.tilt': 19,
        'surf.type': 'basic',
        'surf.contrast': 106,
        'surf.brightness': -26,
        'surf.invert': false,
        'surf.complexity': 2.6,
        'surf.subInfluence': 45,
        'surf.subScaling': 61,
        'surf.subRotation': 46,
        'surf.scale': 35,
        'surf.stretchW': 71,
        'surf.stretchH': 53,
        'surf.rotation': 0,
        'surf.offsetX': 0,
        'surf.offsetY': 0,
        'surf.flowX': 0,
        'surf.flowY': 0,
        'surf.evolution': 0,
        'surf.evoSpeed': 2.23,
        'surf.warp': 0.91,
        'surf.bands': 5,
        'surf.bandSoft': 0,
        'surf.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#ffe0f0',
          },
          {
            pos: 0.5,
            color: '#ff6ac8',
          },
          {
            pos: 0.75,
            color: '#e01a8a',
          },
          {
            pos: 1,
            color: '#6b0f4a',
          },
        ],
        'surf.alpha': 'luma',
        'surf.quality': 'normal',
        'outline.mode': 'off',
        'outline.px': 1.5,
        'outline.colorMode': 'darken',
        'outline.darken': 0.52,
        'outline.color': '#1a0e12',
        'dissolve.mode': 'off',
        'dissolve.direction': 'dissolve',
        'dissolve.amount': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.45,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'dissolve.size': 54,
        'dissolve.angle': 0,
        'dissolve.roughness': 0.4,
        'dissolve.flow': 0.85,
        'dissolve.edgePx': 0,
        'dissolve.edgeColor': '#fff4c2',
        'dissolve.edgeNoise': 0,
        'dissolve.edgeDetail': 1.55,
        'dissolve.edgeWobble': 0.25,
        'glow.amount': 0.82,
        'glow.radius': 22,
        'glow.core': 0.71,
        'glow.tint': '#ffffff00',
        'orbit.count': 12,
        'orbit.radius': 167,
        'orbit.radiusVariance': 0.27,
        'orbit.speed': 2.7,
        'orbit.speedVariance': 0.19,
        'orbit.startAngle': 0,
        'orbit.spread': 360,
        'orbit.jitter': 0.97,
        'orbit.tilt': 89,
        'orbit.planeAngle': -25,
        'orbit.depthScale': 0.54,
        'orbit.depthFade': 0.55,
        'orbit.depthShade': 0.21,
        'orbit.show': 'all',
        'orbit.pulse': 0,
        'orbit.pulseSpeed': 0.6,
        'orbit.alignToPath': true,
        'orbit.size': 0.84,
        'orbit.sizeVariance': 0.13,
        'orbit.x': 0,
        'orbit.y': 0,
        'orbit.start': 0,
        'orbit.end': 0.97,
        'orbit.scaleOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.24920307274247494,
            y: 1.972311580882353,
          },
          {
            x: 0.5105429556856188,
            y: 1.2104779411764708,
          },
          {
            x: 1,
            y: 0,
          },
        ],
        'orbit.opacityOverLife': [
          {
            x: 0,
            y: 0.014705882352941131,
          },
          {
            x: 0.15431647157190637,
            y: 1,
          },
          {
            x: 0.5466137123745819,
            y: 0.31979549632352944,
          },
          {
            x: 1,
            y: 0.024931066176470548,
          },
        ],
      },
    },
    {
      id: 'debris',
      label: 'Debris',
      type: 'debrisBurst',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'add',
      anchor: 'afterImpact',
      seedKey: 'debris~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: null,
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {},
      params: {
        'debris.size': 3.5,
        'debris.vertices': 7,
        'debris.irregularity': 0.44,
        'debris.spin': 405,
        'tex.size': 122,
        'tex.play': 'loop',
        'tex.fps': 29,
        'tex.randomStart': true,
        'tex.color': 'original',
        'tex.angle': 0,
        'style.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#d6fff0',
          },
          {
            pos: 0.5,
            color: '#3affb8',
          },
          {
            pos: 0.75,
            color: '#1ab87a',
          },
          {
            pos: 1,
            color: '#0f4a4a',
          },
        ],
        'style.rampOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'style.spread': 0.2,
        'style.bands': 5,
        'style.bandNoise': 0.45,
        'style.snapColors': false,
        'shade.light': 360,
        'shade.shadow': 0.28,
        'shade.shadowOffset': 0.25,
        'shade.highlight': 0,
        'shade.highlightSize': 0.29,
        'shade.highlightOffset': 0.24,
        'goo.amount': 0,
        'goo.threshold': 0.39,
        'goo.softness': 0.025,
        'goo.keepShapes': true,
        'surf.on': false,
        'surf.map': 'flow',
        'surf.blend': 'normal',
        'surf.mix': 92,
        'surf.flowAngle': -111,
        'surf.flowSpeed': 403,
        'surf.flowStretch': 4.5,
        'surf.radius': 0,
        'surf.spin': 0.09,
        'surf.tilt': 21,
        'surf.type': 'basic',
        'surf.contrast': 89,
        'surf.brightness': -39,
        'surf.invert': false,
        'surf.complexity': 2.4,
        'surf.subInfluence': 73,
        'surf.subScaling': 65,
        'surf.subRotation': 30,
        'surf.scale': 50,
        'surf.stretchW': 150,
        'surf.stretchH': 82,
        'surf.rotation': 0,
        'surf.offsetX': 0,
        'surf.offsetY': 0,
        'surf.flowX': 0,
        'surf.flowY': 0,
        'surf.evolution': 0,
        'surf.evoSpeed': 2.07,
        'surf.warp': 0.72,
        'surf.bands': 2,
        'surf.bandSoft': 0,
        'surf.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#ffe0f0',
          },
          {
            pos: 0.5,
            color: '#ff6ac8',
          },
          {
            pos: 0.75,
            color: '#e01a8a',
          },
          {
            pos: 1,
            color: '#6b0f4a',
          },
        ],
        'surf.alpha': 'luma',
        'surf.quality': 'normal',
        'outline.mode': 'outer',
        'outline.px': 1,
        'outline.colorMode': 'darken',
        'outline.darken': 0.34,
        'outline.color': '#1a0e12',
        'dissolve.mode': 'off',
        'dissolve.direction': 'dissolve',
        'dissolve.amount': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.45,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'dissolve.size': 44,
        'dissolve.angle': 0,
        'dissolve.roughness': 0.46,
        'dissolve.flow': 0.4,
        'dissolve.edgePx': 0,
        'dissolve.edgeColor': '#fff4c2',
        'dissolve.edgeNoise': 0,
        'dissolve.edgeDetail': 0.75,
        'dissolve.edgeWobble': 0.45,
        'glow.amount': 0,
        'glow.radius': 20,
        'glow.core': 0.45,
        'glow.tint': '#ffffff00',
        'burst.count': 32,
        'burst.start': 0,
        'burst.window': 0,
        'burst.spawnRadius': 0,
        'burst.direction': 0,
        'burst.cone': 290,
        'burst.speed': 455,
        'burst.speedVariance': 1,
        'burst.drag': 1,
        'burst.gravity': 0,
        'burst.buoyancy': 0,
        'burst.life': 0.65,
        'burst.lifeVariance': 0.22,
        'burst.size': 0.71,
        'burst.sizeVariance': 0.9,
        'burst.alignToVelocity': false,
        'burst.randomRotation': 278,
        'burst.spin': 0,
        'burst.scaleOverLife': [
          {
            x: 0,
            y: 0.3,
          },
          {
            x: 0.2,
            y: 1,
          },
          {
            x: 1,
            y: 0.6,
          },
        ],
        'burst.opacityOverLife': [
          {
            x: 0,
            y: 1,
          },
          {
            x: 0.75,
            y: 1,
          },
          {
            x: 1,
            y: 0,
          },
        ],
      },
    },
    {
      id: 'sparks',
      label: 'Sparks',
      type: 'streakBurst',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'normal',
      anchor: 'afterImpact',
      seedKey: 'sparks~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: null,
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {},
      params: {
        'streak.length': 34,
        'streak.thickness': 7.5,
        'streak.taper': 0.94,
        'tex.size': 177,
        'tex.play': 'loop',
        'tex.fps': 17,
        'tex.randomStart': true,
        'tex.color': 'original',
        'tex.angle': 0,
        'style.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#d6fff0',
          },
          {
            pos: 0.5,
            color: '#3affb8',
          },
          {
            pos: 0.75,
            color: '#1ab87a',
          },
          {
            pos: 1,
            color: '#0f4a4a',
          },
        ],
        'style.rampOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'style.spread': 0.46,
        'style.bands': 1,
        'style.bandNoise': 0.23,
        'style.snapColors': false,
        'shade.light': 290,
        'shade.shadow': 0,
        'shade.shadowOffset': 0.11,
        'shade.highlight': 0,
        'shade.highlightSize': 0.22,
        'shade.highlightOffset': 0.45,
        'goo.amount': 0,
        'goo.threshold': 0.55,
        'goo.softness': 0.06,
        'goo.keepShapes': true,
        'surf.on': false,
        'surf.map': 'flow',
        'surf.blend': 'normal',
        'surf.mix': 100,
        'surf.flowAngle': -96,
        'surf.flowSpeed': 392,
        'surf.flowStretch': 2.9,
        'surf.radius': 0,
        'surf.spin': 0.16,
        'surf.tilt': 22,
        'surf.type': 'basic',
        'surf.contrast': 216,
        'surf.brightness': -20,
        'surf.invert': false,
        'surf.complexity': 5.3,
        'surf.subInfluence': 41,
        'surf.subScaling': 29,
        'surf.subRotation': 54,
        'surf.scale': 56,
        'surf.stretchW': 84,
        'surf.stretchH': 128,
        'surf.rotation': 0,
        'surf.offsetX': 0,
        'surf.offsetY': 0,
        'surf.flowX': 0,
        'surf.flowY': 0,
        'surf.evolution': 0,
        'surf.evoSpeed': 1.56,
        'surf.warp': 0.52,
        'surf.bands': 3,
        'surf.bandSoft': 0,
        'surf.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#ffe0f0',
          },
          {
            pos: 0.5,
            color: '#ff6ac8',
          },
          {
            pos: 0.75,
            color: '#e01a8a',
          },
          {
            pos: 1,
            color: '#6b0f4a',
          },
        ],
        'surf.alpha': 'luma',
        'surf.quality': 'normal',
        'outline.mode': 'off',
        'outline.px': 3.5,
        'outline.colorMode': 'darken',
        'outline.darken': 0.36,
        'outline.color': '#1a0e12',
        'dissolve.mode': 'off',
        'dissolve.direction': 'dissolve',
        'dissolve.amount': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.45,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'dissolve.size': 24,
        'dissolve.angle': 0,
        'dissolve.roughness': 0.14,
        'dissolve.flow': 0.6,
        'dissolve.edgePx': 0,
        'dissolve.edgeColor': '#fff4c2',
        'dissolve.edgeNoise': 0,
        'dissolve.edgeDetail': 1.65,
        'dissolve.edgeWobble': 0.85,
        'glow.amount': 0,
        'glow.radius': 40,
        'glow.core': 0.55,
        'glow.tint': '#ffffff00',
        'burst.count': 23,
        'burst.start': 0,
        'burst.window': 0,
        'burst.spawnRadius': 0,
        'burst.direction': 0,
        'burst.cone': 360,
        'burst.speed': 470,
        'burst.speedVariance': 0.46,
        'burst.drag': 4.3,
        'burst.gravity': 210,
        'burst.buoyancy': 0,
        'burst.life': 0.38,
        'burst.lifeVariance': 0.21,
        'burst.size': 0.81,
        'burst.sizeVariance': 0.46,
        'burst.alignToVelocity': true,
        'burst.randomRotation': 360,
        'burst.spin': 0,
        'burst.scaleOverLife': [
          {
            x: 0,
            y: 0.3,
          },
          {
            x: 0.2,
            y: 1,
          },
          {
            x: 1,
            y: 0.6,
          },
        ],
        'burst.opacityOverLife': [
          {
            x: 0,
            y: 1,
          },
          {
            x: 0.75,
            y: 1,
          },
          {
            x: 1,
            y: 0,
          },
        ],
      },
    },
    {
      id: 'anticipation',
      label: 'Anticipation glow',
      type: 'blob',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'add',
      anchor: 'anticipation',
      seedKey: 'anticipation~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: null,
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {},
      params: {
        'blob.radius': 72,
        'blob.noise': 0.07,
        'blob.frequency': 2.3,
        'blob.lobes': 0,
        'blob.lobeDepth': 0.09,
        'blob.wobble': 1.75,
        'tex.size': 143,
        'tex.play': 'loop',
        'tex.fps': 20,
        'tex.randomStart': true,
        'tex.color': 'original',
        'tex.angle': 0,
        'style.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#d6fff0',
          },
          {
            pos: 0.5,
            color: '#3affb8',
          },
          {
            pos: 0.75,
            color: '#1ab87a',
          },
          {
            pos: 1,
            color: '#0f4a4a',
          },
        ],
        'style.rampOverLife': [
          {
            x: 0,
            y: 0.8,
          },
          {
            x: 1,
            y: 0,
          },
        ],
        'style.spread': 0.41,
        'style.bands': 1,
        'style.bandNoise': 0.14,
        'style.snapColors': false,
        'shade.light': 263,
        'shade.shadow': 0,
        'shade.shadowOffset': 0.19,
        'shade.highlight': 0,
        'shade.highlightSize': 0.18,
        'shade.highlightOffset': 0.23,
        'goo.amount': 0,
        'goo.threshold': 0.33,
        'goo.softness': 0.055,
        'goo.keepShapes': true,
        'surf.on': false,
        'surf.map': 'flow',
        'surf.blend': 'normal',
        'surf.mix': 100,
        'surf.flowAngle': -91,
        'surf.flowSpeed': 499,
        'surf.flowStretch': 3.9,
        'surf.radius': 0,
        'surf.spin': 0.11,
        'surf.tilt': 36,
        'surf.type': 'basic',
        'surf.contrast': 211,
        'surf.brightness': -26,
        'surf.invert': false,
        'surf.complexity': 2.3,
        'surf.subInfluence': 63,
        'surf.subScaling': 52,
        'surf.subRotation': 44,
        'surf.scale': 53,
        'surf.stretchW': 125,
        'surf.stretchH': 72,
        'surf.rotation': 0,
        'surf.offsetX': 0,
        'surf.offsetY': 0,
        'surf.flowX': 0,
        'surf.flowY': 0,
        'surf.evolution': 0,
        'surf.evoSpeed': 1.04,
        'surf.warp': 1.53,
        'surf.bands': 3,
        'surf.bandSoft': 0,
        'surf.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#ffe0f0',
          },
          {
            pos: 0.5,
            color: '#ff6ac8',
          },
          {
            pos: 0.75,
            color: '#e01a8a',
          },
          {
            pos: 1,
            color: '#6b0f4a',
          },
        ],
        'surf.alpha': 'luma',
        'surf.quality': 'normal',
        'outline.mode': 'off',
        'outline.px': 2.5,
        'outline.colorMode': 'darken',
        'outline.darken': 1,
        'outline.color': '#1a0e12',
        'dissolve.mode': 'off',
        'dissolve.direction': 'dissolve',
        'dissolve.amount': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.45,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'dissolve.size': 37,
        'dissolve.angle': 0,
        'dissolve.roughness': 0.17,
        'dissolve.flow': 0.8,
        'dissolve.edgePx': 0,
        'dissolve.edgeColor': '#fff4c2',
        'dissolve.edgeNoise': 0,
        'dissolve.edgeDetail': 0.65,
        'dissolve.edgeWobble': 0.85,
        'glow.amount': 0,
        'glow.radius': 20,
        'glow.core': 0.92,
        'glow.tint': '#ffffff00',
        'single.start': 0,
        'single.end': 1,
        'single.scaleOverLife': [
          {
            x: 0,
            y: 0.2,
          },
          {
            x: 0.7,
            y: 1,
          },
          {
            x: 1,
            y: 0.35,
          },
        ],
        'single.opacityOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.3,
            y: 0.8,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'single.x': 0,
        'single.y': 0,
        'single.rotation': 0,
        'single.scale': 1,
      },
    },
    {
      id: 'flash',
      label: 'Impact flash',
      type: 'blob',
      enabled: true,
      solo: false,
      opacity: 1,
      blend: 'normal',
      anchor: 'flash',
      seedKey: 'flash~jfhhyb',
      transform: {
        x: 0,
        y: 0,
        anchorX: 0,
        anchorY: 0,
        scaleX: 100,
        scaleY: 100,
        rotation: 0,
      },
      parent: null,
      time: {
        offset: 0,
        stretch: 1,
        in: 0,
        out: null,
      },
      keys: {},
      params: {
        'blob.radius': 203,
        'blob.noise': 0.06,
        'blob.frequency': 0.2,
        'blob.lobes': 0,
        'blob.lobeDepth': 0.09,
        'blob.wobble': 0.8,
        'tex.size': 51,
        'tex.play': 'loop',
        'tex.fps': 30,
        'tex.randomStart': true,
        'tex.color': 'original',
        'tex.angle': 0,
        'style.ramp': [
          {
            pos: 0,
            color: '#bff1ff',
          },
          {
            pos: 0.25,
            color: '#3fb4e8',
          },
          {
            pos: 0.5,
            color: '#1e6fbf',
          },
          {
            pos: 0.75,
            color: '#17438a',
          },
          {
            pos: 1,
            color: '#101f4a',
          },
        ],
        'style.rampOverLife': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'style.spread': 0,
        'style.bands': 1,
        'style.bandNoise': 0.3,
        'style.snapColors': false,
        'shade.light': 329,
        'shade.shadow': 0,
        'shade.shadowOffset': 0.15,
        'shade.highlight': 0,
        'shade.highlightSize': 0.46,
        'shade.highlightOffset': 0.32,
        'goo.amount': 0,
        'goo.threshold': 0.5,
        'goo.softness': 0.025,
        'goo.keepShapes': true,
        'surf.on': false,
        'surf.map': 'flow',
        'surf.blend': 'normal',
        'surf.mix': 100,
        'surf.flowAngle': -90,
        'surf.flowSpeed': 385,
        'surf.flowStretch': 3.4,
        'surf.radius': 0,
        'surf.spin': 0.17,
        'surf.tilt': 36,
        'surf.type': 'basic',
        'surf.contrast': 250,
        'surf.brightness': -32,
        'surf.invert': false,
        'surf.complexity': 4.5,
        'surf.subInfluence': 71,
        'surf.subScaling': 49,
        'surf.subRotation': 45,
        'surf.scale': 49,
        'surf.stretchW': 79,
        'surf.stretchH': 148,
        'surf.rotation': 0,
        'surf.offsetX': 0,
        'surf.offsetY': 0,
        'surf.flowX': 0,
        'surf.flowY': 0,
        'surf.evolution': 0,
        'surf.evoSpeed': 0.85,
        'surf.warp': 1.81,
        'surf.bands': 3,
        'surf.bandSoft': 0,
        'surf.ramp': [
          {
            pos: 0,
            color: '#ffffff',
          },
          {
            pos: 0.25,
            color: '#ffe0f0',
          },
          {
            pos: 0.5,
            color: '#ff6ac8',
          },
          {
            pos: 0.75,
            color: '#e01a8a',
          },
          {
            pos: 1,
            color: '#6b0f4a',
          },
        ],
        'surf.alpha': 'luma',
        'surf.quality': 'normal',
        'outline.mode': 'off',
        'outline.px': 3.5,
        'outline.colorMode': 'darken',
        'outline.darken': 1,
        'outline.color': '#1a0e12',
        'dissolve.mode': 'off',
        'dissolve.direction': 'dissolve',
        'dissolve.amount': [
          {
            x: 0,
            y: 0,
          },
          {
            x: 0.45,
            y: 0,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'dissolve.size': 51,
        'dissolve.angle': 0,
        'dissolve.roughness': 0.23,
        'dissolve.flow': 0.65,
        'dissolve.edgePx': 0,
        'dissolve.edgeColor': '#fff4c2',
        'dissolve.edgeNoise': 0,
        'dissolve.edgeDetail': 0.75,
        'dissolve.edgeWobble': 0.65,
        'glow.amount': 0.8,
        'glow.radius': 18,
        'glow.core': 0.58,
        'glow.tint': '#ffffff00',
        'single.start': 0,
        'single.end': 1,
        'single.scaleOverLife': [
          {
            x: 0,
            y: 1,
          },
          {
            x: 1,
            y: 1.15,
          },
        ],
        'single.opacityOverLife': [
          {
            x: 0,
            y: 1,
          },
          {
            x: 1,
            y: 1,
          },
        ],
        'single.x': 0,
        'single.y': 0,
        'single.rotation': 0,
        'single.scale': 1,
      },
    },
  ],
};
